### ISSUE TITLE
Can we get SHA256 and SHA1 added ?

### ISSUE THREAD

**Issue by RKO1195** [cmelone/marlin#1]
Hi 

Can we get the SHA1 and SHA256 added to the packages.gz file ? I just found this nice tool and it's a big help to me but noticed it didn't add the other two SHA1 and SHA256 sums and Cydia uses them now. Thanks for your work and time on this great tool.

**Comment by cmelone** [comment]
Yep, I'll look into.

**Comment by RKO1195** [comment]
Ok really appreciate it. Thanks  

If it will help I need it for Linux for my server.

**Comment by cmelone** [comment]
This package is no longer maintained.
