### ISSUE TITLE
A suggestion 

### ISSUE THREAD

**Issue by jailbreakgroup** [cmelone/marlin#2]
what if i already had tweaks on packages file before i run the script? for the new debs files, the old file will be completely modified? cuz i may change the description and i don't want to change it?
i mean if you just leave description empty its much better..

Icon: not shown all the time..

Depiction:  https://USER.github.io/depictions/?p=(com.packge) (for GitHub hosted repos) by default
LETS JUST SAY I CAN SET MY REPO BEFORE I START RUNNING SCRIPT  

also if you add SHA1 and SHA256 that would be a lot awesome man.

it helps me a lot so i feel like i have to drop this to you
thank you in advance

**Comment by cmelone** [comment]
This package is no longer maintained.
